/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ciel_microservices_dispatch_engine_service_mod_route_ModRouteEngine */

#ifndef _Included_com_ciel_microservices_dispatch_engine_service_mod_route_ModRouteEngine
#define _Included_com_ciel_microservices_dispatch_engine_service_mod_route_ModRouteEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ciel_microservices_dispatch_engine_service_mod_route_ModRouteEngine
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ciel_microservices_dispatch_1engine_1service_mod_1route_ModRouteEngine_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_ciel_microservices_dispatch_engine_service_mod_route_ModRouteEngine
 * Method:    runOptimize
 * Signature: (Lcom/ciel/microservices/dispatch_engine_service/mod_route/ModRequest;Ljava/lang/String;Lcom/ciel/microservices/dispatch_engine_service/mod_route/RouteType;ILjava/lang/String;Lcom/ciel/microservices/dispatch_engine_service/mod_route/AlgorithmParameters;Lcom/ciel/microservices/dispatch_engine_service/mod_route/ModRouteConfiguration;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_ciel_microservices_dispatch_1engine_1service_mod_1route_ModRouteEngine_runOptimize
  (JNIEnv *, jobject, jobject, jstring, jobject, jint, jstring, jobject, jobject);

/*
 * Class:     com_ciel_microservices_dispatch_engine_service_mod_route_ModRouteEngine
 * Method:    clearCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ciel_microservices_dispatch_1engine_1service_mod_1route_ModRouteEngine_clearCache
  (JNIEnv *, jobject);

/*
 * Class:     com_ciel_microservices_dispatch_engine_service_mod_route_ModRouteEngine
 * Method:    default_algorithm_parameters
 * Signature: ()Lcom/ciel/microservices/dispatch_engine_service/mod_route/AlgorithmParameters;
 */
JNIEXPORT jobject JNICALL Java_com_ciel_microservices_dispatch_1engine_1service_mod_1route_ModRouteEngine_default_1algorithm_1parameters
  (JNIEnv *, jobject);

/*
 * Class:     com_ciel_microservices_dispatch_engine_service_mod_route_ModRouteEngine
 * Method:    default_mod_route_configuration
 * Signature: ()Lcom/ciel/microservices/dispatch_engine_service/mod_route/ModRouteConfiguration;
 */
JNIEXPORT jobject JNICALL Java_com_ciel_microservices_dispatch_1engine_1service_mod_1route_ModRouteEngine_default_1mod_1route_1configuration
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
